# ╭─ ♪ Symphony ─╮
# │  Generated   │
# ╰──────────────╯
# Theme: Omarchy osaka-jade (omarchy)

background #111C18
foreground #C1C497
selection_background #2DD5B7
selection_foreground #111C18
cursor #C1C497
cursor_text_color #111C18
active_tab_background #509475
active_tab_foreground #111C18
inactive_tab_background #53685B
inactive_tab_foreground #F6F5DD
active_border_color #509475
inactive_border_color #53685B
color0 #23372B
color1 #FF5345
color2 #549E6A
color3 #459451
color4 #509475
color5 #D2689C
color6 #2DD5B7
color7 #F6F5DD
color8 #53685B
color9 #DB9F9C
color10 #63b07a
color11 #E5C736
color12 #ACD4CF
color13 #75BBB3
color14 #8CD3CB
color15 #9EEBB3
