-- ────────────────────────────────────────────────────────────
-- Omarchy Custom Theme for Neovim
-- Generated by Omarchist
-- ────────────────────────────────────────────────────────────

return {
	{
		"bjarneo/aether.nvim",
		name = "demon",
		priority = 1000,
		opts = {
			disable_italics = false,
			colors = {
				-- Core monochrome shades
				base00 = "#0F0F0F", -- Background
				base01 = "#1B1B1B", -- Panels
				base02 = "#3A403B", -- Selection
				base03 = "#6E6A5A", -- Comments
				base04 = "#7B726A", -- Dim text
				base05 = "#E0D4C2", -- Foreground
				base06 = "#F3E9DA", -- Bright fg
				base07 = "#FFFFFF", -- White

				-- Accents (adjusted for readability)
				base08 = "#CC3A3A", -- Errors (was #8B0000) softer but still strong
				base09 = "#E89A24", -- Constants (less neon)
				base0A = "#D77A22", -- Keywords (warm amber, not red)
				base0B = "#C99A6C", -- Strings (tan, earthy, readable)
				base0C = "#A67C52", -- Support (unchanged)
				base0D = "#C9694A", -- Functions (copper, not tomato red)
				base0E = "#8F4A2F", -- Alt keywords (deep warm brown, not red)
				base0F = "#A14C2D", -- Deprecated (muted rust)
			},
		},
		config = function(_, opts)
			require("aether").setup(opts)
			vim.cmd.colorscheme("aether")
			require("aether.hotreload").setup()
		end,
	},
	{
		"LazyVim/LazyVim",
		opts = { colorscheme = "aether" },
	},
}