# ╭─ ♪ Symphony ─╮
# │  Generated   │
# ╰──────────────╯
# Theme: Omarchy blackturq (omarchy)

background #0a0a0a
foreground #DAF6F4
selection_background #7cf0ef
selection_foreground #0a0a0a
cursor #DAF6F4
cursor_text_color #0a0a0a
active_tab_background #ADF0E9
active_tab_foreground #0a0a0a
inactive_tab_background #322F3B
inactive_tab_foreground #646d7a
active_border_color #ADF0E9
inactive_border_color #322F3B
color0 #0a0a0a
color1 #D35F5F
color2 #8FECD5
color3 #A9D1D7
color4 #ADF0E9
color5 #485362
color6 #7cf0ef
color7 #646d7a
color8 #322F3B
color9 #D35F5F
color10 #8FECD5
color11 #A9D1D7
color12 #ADF0E9
color13 #485362
color14 #7cf0ef
color15 #646d7a
