# ╭─ ♪ Symphony ─╮
# │  Generated   │
# ╰──────────────╯
# Theme: Omarchy demon (omarchy)

background #0F0F0F
foreground #E0D4C2
selection_background #7A7D80
selection_foreground #0F0F0F
cursor #E0D4C2
cursor_text_color #0F0F0F
active_tab_background #4A4E3D
active_tab_foreground #0F0F0F
inactive_tab_background #292828
inactive_tab_foreground #BDB5AA
active_border_color #4A4E3D
inactive_border_color #292828
color0 #0F0F0F
color1 #8B0000
color2 #3A403B
color3 #E24C00
color4 #4A4E3D
color5 #7B726A
color6 #7A7D80
color7 #BDB5AA
color8 #292828
color9 #8B0000
color10 #305432
color11 #E24C00
color12 #496529
color13 #7B726A
color14 #7A7D80
color15 #BDB5AA
