# ╭─ ♪ Symphony ─╮
# │  Generated   │
# ╰──────────────╯
# Theme: Omarchy osaka-jade (omarchy)

$activeBorderColor = rgba(509475aa)
general { col.active_border = $activeBorderColor }
group { col.border_active = $activeBorderColor }
$secondary = $activeBorderColor
$outline_variant = rgba(53685Bff)
decoration {
    shadow {
        color = rgba(111C1880)
        color_inactive = rgba(111C184d)
        offset = 2 2
        range = 20
        render_power = 3
    }
}
