;; ╭─ ♪ Symphony ─╮
;; │  Generated   │
;; ╰──────────────╯
;; Theme: Omarchy demon (omarchy)

[base]
text               = E0D4C2
subtext            = 292828
nav-active-text    = 4A4E3D
main               = 0F0F0F
sidebar            = 0F0F0F
player             = 0F0F0F
card               = 0F0F0F
shadow             = 000000
main-secondary     = 0F0F0F
button             = 232323
button-secondary   = 7A7D80
button-active      = 4A4E3D
button-disabled    = 050505
nav-active         = 232323
play-button        = 4A4E3D
tab-active         = 0F0F0F
notification       = 0F0F0F
notification-error = 0F0F0F
playback-bar       = 4A4E3D
misc               = 292828
