;; ╭─ ♪ Symphony ─╮
;; │  Generated   │
;; ╰──────────────╯
;; Theme: Omarchy deadspace (omarchy)

[base]
text               = ffffff
subtext            = dddbdb
nav-active-text    = c1baba
main               = 010101
sidebar            = 010101
player             = 010101
card               = 010101
shadow             = 000000
main-secondary     = 010101
button             = 151515
button-secondary   = dedada
button-active      = c1baba
button-disabled    = 000000
nav-active         = 151515
play-button        = c1baba
tab-active         = 010101
notification       = 010101
notification-error = 010101
playback-bar       = c1baba
misc               = dddbdb
