;; ╭─ ♪ Symphony ─╮
;; │  Generated   │
;; ╰──────────────╯
;; Theme: Omarchy blackturq (omarchy)

[base]
text               = DAF6F4
subtext            = 322F3B
nav-active-text    = ADF0E9
main               = 0a0a0a
sidebar            = 0a0a0a
player             = 0a0a0a
card               = 0a0a0a
shadow             = 000000
main-secondary     = 0a0a0a
button             = 1e1e1e
button-secondary   = 7cf0ef
button-active      = ADF0E9
button-disabled    = 000000
nav-active         = 1e1e1e
play-button        = ADF0E9
tab-active         = 0a0a0a
notification       = 0a0a0a
notification-error = 0a0a0a
playback-bar       = ADF0E9
misc               = 322F3B
