# ╭─ ♪ Symphony ─╮
# │  Generated   │
# ╰──────────────╯
# Theme: Omarchy deadspace (omarchy)

background #010101
foreground #ffffff
selection_background #dedada
selection_foreground #010101
cursor #ffffff
cursor_text_color #010101
active_tab_background #c1baba
active_tab_foreground #010101
inactive_tab_background #dddbdb
inactive_tab_foreground #F6F6F5
active_border_color #c1baba
inactive_border_color #dddbdb
color0 #010101
color1 #958a8a
color2 #a49a9a
color3 #b2aaaa
color4 #c1baba
color5 #cfcaca
color6 #dedada
color7 #F6F6F5
color8 #dddbdb
color9 #ada5a5
color10 #bcb5b5
color11 #cac5c5
color12 #d9d5d5
color13 #e7e5e5
color14 #f6f5f5
color15 #ffffff
