;; ╭─ ♪ Symphony ─╮
;; │  Generated   │
;; ╰──────────────╯
;; Theme: Omarchy osaka-jade (omarchy)

[base]
text               = C1C497
subtext            = 53685B
nav-active-text    = 509475
main               = 111C18
sidebar            = 111C18
player             = 111C18
card               = 111C18
shadow             = 000000
main-secondary     = 111C18
button             = 25302c
button-secondary   = 2DD5B7
button-active      = 509475
button-disabled    = 07120e
nav-active         = 25302c
play-button        = 509475
tab-active         = 111C18
notification       = 111C18
notification-error = 111C18
playback-bar       = 509475
misc               = 53685B
